// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHCMt-8EKcWRL_0gpQ_hw4cxG2tDfytD0',
    appId: '1:584944356393:web:f5ea64d5fb5ac8019ee038',
    messagingSenderId: '584944356393',
    projectId: 'powerliftingcalendar-mvp',
    authDomain: 'powerliftingcalendar-mvp.firebaseapp.com',
    storageBucket: 'powerliftingcalendar-mvp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXXL3nQgdud3ZakKVAa0KP9gD0pTBlBFk',
    appId: '1:584944356393:android:ed9ed176d4bb4c2b9ee038',
    messagingSenderId: '584944356393',
    projectId: 'powerliftingcalendar-mvp',
    storageBucket: 'powerliftingcalendar-mvp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzA9fQCL5JbG9hgqj9Y8vKHqBJrhebRB4',
    appId: '1:584944356393:ios:2794fdef1874ec649ee038',
    messagingSenderId: '584944356393',
    projectId: 'powerliftingcalendar-mvp',
    storageBucket: 'powerliftingcalendar-mvp.firebasestorage.app',
    androidClientId: '584944356393-9si9gp4h61lndam18iskl35e2nkrq59i.apps.googleusercontent.com',
    iosClientId: '584944356393-6r2p4fee1st5sd5biqqj81s08ic6mrkn.apps.googleusercontent.com',
    iosBundleId: 'com.mycompany.powerliftingmvp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHCMt-8EKcWRL_0gpQ_hw4cxG2tDfytD0',
    appId: '1:584944356393:web:bcf689a91ca8e4a49ee038',
    messagingSenderId: '584944356393',
    projectId: 'powerliftingcalendar-mvp',
    authDomain: 'powerliftingcalendar-mvp.firebaseapp.com',
    storageBucket: 'powerliftingcalendar-mvp.firebasestorage.app',
  );
}
